language: java

jdk:
  - openjdk13

before_install:
  - cd elasticsearch-sql-core

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true

script:
  - ulimit -a
  - mvn test